name: release_clang
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: installdeps
      run: sudo ./build.sh installdeps
    - name: setcompiler
      run: export CC=/usr/bin/clang
    - name: build
      run: ./build.sh release
    - name: install
      run: sudo ./build.sh install
